CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    last_login TIMESTAMP,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE claims (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    claim_date TIMESTAMP NOT NULL,
    claim_amount NUMERIC(19, 2) NOT NULL,
    email_id VARCHAR(255),
    claim_type VARCHAR(100) NOT NULL,
    claim_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    last_updated TIMESTAMP NOT NULL,
    idempotency_key VARCHAR(128),
    CONSTRAINT fk_claims_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uk_claims_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT chk_claims_status CHECK (
        claim_status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SETTLED')
    ),
    CONSTRAINT chk_claims_amount_positive CHECK (claim_amount > 0)
);

CREATE TABLE claim_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL,
    previous_status VARCHAR(32) NOT NULL,
    new_status VARCHAR(32) NOT NULL,
    changed_by VARCHAR(100) NOT NULL,
    reason VARCHAR(500),
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_claim_status_history_claim FOREIGN KEY (claim_id) REFERENCES claims (claim_id),
    CONSTRAINT chk_claim_history_previous_status CHECK (
        previous_status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SETTLED')
    ),
    CONSTRAINT chk_claim_history_new_status CHECK (
        new_status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SETTLED')
    )
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE claim_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    total_claims BIGINT NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    report_date TIMESTAMP NOT NULL,
    CONSTRAINT chk_claim_reports_status CHECK (
        status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SETTLED')
    )
);

CREATE TABLE claims_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_generated TIMESTAMP NOT NULL,
    number_of_claims INTEGER NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL
);

CREATE INDEX idx_claims_user_id ON claims (user_id);
CREATE INDEX idx_claims_status ON claims (claim_status);
CREATE INDEX idx_claims_type ON claims (claim_type);
CREATE INDEX idx_claims_status_last_updated ON claims (claim_status, last_updated);
CREATE INDEX idx_claim_history_claim_changed ON claim_status_history (claim_id, changed_at);
CREATE INDEX idx_notifications_user_timestamp ON notifications (user_id, timestamp);
CREATE INDEX idx_claim_reports_status_date ON claim_reports (status, report_date);
CREATE INDEX idx_claims_summaries_generated ON claims_summaries (report_generated);
