UPDATE users SET role = 'CLAIMANT'
WHERE UPPER(role) IN ('USER', 'ROLE_USER', 'CLAIMANT', 'ROLE_CLAIMANT');

UPDATE users SET role = 'CLAIMS_OFFICER'
WHERE UPPER(role) IN ('OFFICER', 'ROLE_OFFICER', 'CLAIMS_OFFICER', 'ROLE_CLAIMS_OFFICER');

UPDATE users SET role = 'ADMIN'
WHERE UPPER(role) IN ('ADMIN', 'ROLE_ADMIN');

UPDATE users SET role = 'CLAIMANT'
WHERE role NOT IN ('CLAIMANT', 'CLAIMS_OFFICER', 'ADMIN');

ALTER TABLE users ADD CONSTRAINT chk_users_role
CHECK (role IN ('CLAIMANT', 'CLAIMS_OFFICER', 'ADMIN'));
