-- Transactional outbox: status events are written in the same transaction as the claim
-- change and relayed to Kafka afterwards, so a crash between commit and send cannot lose them.
CREATE TABLE claim_status_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL,
    claim_id BIGINT NOT NULL,
    previous_status VARCHAR(32) NOT NULL,
    new_status VARCHAR(32) NOT NULL,
    user_id BIGINT,
    user_email VARCHAR(255),
    changed_by VARCHAR(100) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000),
    CONSTRAINT uk_claim_status_outbox_event_id UNIQUE (event_id)
);

-- Supports both the relay's "unpublished, oldest first" scan and retention cleanup.
CREATE INDEX idx_claim_status_outbox_published_id
    ON claim_status_outbox (published_at, id);
